spring:
 application:
  name: hoteles
 datasource:
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://JJCuadrado-W10\SQLEXPRESS;databaseName=viajes
  username: sa
  password: telynet
 jpa:
  show-sql: true
  hibernate:
   dialect: org.hibernate.dialect.SQLServer2012Dialect
   naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
   naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
 port: 5001
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
 instance:
  instance-id: 1
